language: php
php:
- 5.4
before_install:
- openssl aes-256-cbc -K $encrypted_a9612bbdf61a_key -iv $encrypted_a9612bbdf61a_iv
  -in service-key.json.enc -out service-key.json -d
sudo: required
before_script:
  - ./setup/apache.sh
  - ./setup/selenium.sh

deploy:
  provider: gae
  keyfile: "service-key.json" 
  default: true
  project: logical-iridium-107208
