language: php
php:
- 5.4
#before_install:
#- openssl aes-256-cbc -K $encrypted_a9612bbdf61a_key -iv $encrypted_a9612bbdf61a_iv -in service.json.enc -out service.json -d
install:
- pear install pear/PHP_CodeSniffer
- phpenv rehash
sudo: required
before_script:
  - ./setup/apache.sh
  - ./setup/selenium.sh
script:
  - phpunit
  - phpcs
#deploy:
#  provider: gae
#  keyfile: "service.json" 
#  default: true
#  project: logical-iridium-107208
after_success:
    - ssh cgalgo@130.211.246.235 -i identity.pem && touch clark.log

